garnishes = ['apple slice',
 'banana',
 'basil leaf',
 'bing cherry',
 'blackberries',
 'blood orange wheel',
 'canned pitted lychee nut stuffed with a small pineapple leaf',
 'catsup',
 'cayenne pepper',
 'celery stalk',
 'celery stick',
 'cinnamon sugar',
 'clementine or mandarin orange',
 'coarse salt',
 'cucumber',
 'cucumber slice',
 'cucumber slices',
 'egg',
 'egg white',
 'egg yolk',
 'fresh basil leaf',
 'fresh basil leaves',
 'fresh blackberries and raspberries',
 'fresh cherry tomatoes',
 'fresh cilantro leaves',
 'fresh cilantro sprigs',
 'fresh mint leaves',
 'fresh mint sprig',
 'fresh mint sprig dipped in sugar',
 'fresh pomegranate seeds',
 'fresh raspberries and strawberries',
 'fresh raspberry',
 'fresh rosemary sprig',
 'fresh sage leaves',
 'freshly grated nutmeg',
 'freshly ground black pepper',
 'freshly ground black pepper to taste',
 'golden delicious apple wedge',
 'grapefruit twist',
 'green apple slice',
 'green olive',
 'italian preserved cherry',
 'ketchup',
 'lemon',
 'lemon half-wheel',
 'lemon twist',
 'lemon twist (optional)',
 'lemon twiste',
 'lemon wedge',
 'lemon wheel',
 'lemon wheels',
 'lime',
 'lime twist',
 'lime wedge',
 'lime wedges',
 'lime wheel',
 'lime wheel skewered with blueberry and bing cherry',
 'lime wheels',
 'long thyme sprigs',
 'mango slice',
 'maraschino',
 'maraschino cherry',
 'maraschino cherry or lime wheel',
 'mint',
 'mint leaves',
 'mint sprig',
 'orange',
 'orange and lemon wheels',
 'orange and lime wheels',
 'orange half-wheel',
 'orange twist',
 'orange wheel',
 'orange zest',
 'peach',
 'peach slice',
 'peach slices',
 'pepper',
 'pineapple',
 'pineapple chunk',
 'pineapple slice',
 'pineapple slices',
 'pineapple wedge',
 'pineapple wedge skewered with maraschino cherry',
 'powdered nutmeg',
 'powdered sugar',
 'raspberries',
 'raspberry',
 'raspberry and cucumber',
 'red grapes',
 'ripe pear',
 'salt',
 'slice peeled fresh ginger',
 'small pineapple slice',
 'springs mint',
 'stick of cotton candy',
 'strawberries',
 'strawberry',
 'strawberry slice',
 'strawberry slide',
 'sugar',
 'sugar cube',
 'superfine sugar',
 'superfine sugar or coarse salt (optional)',
 'sweet chili powder',
 'sweet pickle slice',
 'thyme sprig',
 'tomato catsup',
 'unsprayed rose petal',
 'whipped cream',
 'whole egg',
 'whole egg and grated nutmet',
 'whole strawberry',
 'wide spiral of lemon zest',
 'wide spiral of orange zest',
 "cocoa",
 'bing cherries',
 'black licorice stick',
 'blueberries',
 'brandied cherry',
 'dill sprig',
 'fresh seasonal fruit',
 'fruits in season',
 'cinnamon stick',
 'cinnamon sticks',
 'cloves',
 'edible flower',
 'edible flowers',
 'generous amount of fresh seasonal fruit',
 'ground cinnamon',
 'rosemary sprig',
 'thin pear slice',
 'whole cloves',
 'shaved ice',
 'white grapes',
 'prepared horseradish']