liquids = ['100-proof vodka',
 '151-proof rum',
 '17-year-old j. wray and nephew ltd. rum',
 '7-up',
 'absinthe',
 'absinthe or pastis',
 'absinthe substitute',
 'acai berry flavored vodka',
 'african rum',
 'agave nectar',
 'aged rhum agricole',
 'allspice liqueur (pimento dram)',
 'almond extract',
 'almond or orgeat syrup',
 'amaretto',
 'amaretto di saronno',
 'amaro',
 'amaro nonino',
 'amer picon or torani amer',
 'anejo tequila',
 'angostura bitters',
 'anis',
 'anisette',
 'aperol',
 'apple brandy',
 'apple cider',
 'apple flavored brandy',
 'apple juice',
 'apple schnapps',
 'applejack',
 'apricot flavored brandy',
 'b & b',
 'bacardi rum',
 'balsamic vinegar',
 'batavia arrack or light rum',
 'benedictine',
 'bitter lemon soda',
 'bitters',
 'black cherry juice',
 'black cherry flavored vodka',
 'black raspberry liqueur',
 'blackberry liqueur',
 'blackberry flavored brandy',
 'blanco tequila',
 'blended scotch whiskey',
 'blended whiskey',
 'blood orange juice',
 'blue curacao',
 'bourbon',
 'bourbon or rye whiskey',
 'bourbon whiskey',
 'brandy',
 'cachaca',
 'calvados',
 'apple brandy or applejack',
 'campari',
 'canadian whisky',
 'carbonated water',
 'champagne',
 'cherry heering',
 'cherry vodka',
 'cherry  flavored brandy',
 'chilled champagne',
 'chilled sparkling wine or champagne',
 'chilled stout',
 'citrus flavored vodka',
 'clam juice',
 'claret',
 'club soda',
 'coconut milk',
 'coconut rum',
 'coconut flavored rum',
 'coffee liqueur',
 'coffee flavored brandy',
 'coffee flavored liqueur',
 'cognac',
 'cola',
 'cold beef bouillon',
 'cold brewed coffee',
 'cold brewed espresso coffee',
 'cold water',
 'concord grape juice',
 'cranberry juice',
 'cream of coconut',
 'cream sherry',
 'crema di limoncello',
 'creme de banana',
 'creme de cacao',
 'creme de cacao (brown)',
 'creme de cacao (white)',
 'creme de cassis',
 'creme de menthe (white)',
 'creme de noyaux',
 'creme de violette',
 'creme yvette',
 'crushed ice',
 'crushed pineapple',
 'curacao',
 'cynar',
 'danish cherry wine',
 'dark creme de cacao',
 'dark rum',
 'demerara syrup',
 'desmond & duff scotch whisky',
 'dry gin',
 'dry sherry',
 'dry vermouth',
 'dubonnet',
 'each cranberry juice and orange juice',
 'each orange juice and sweet sherry',
 'elderflower liqueur',
 'fernet-branca',
 'five star brandy',
 'forbidden fruit',
 'fresh carrot juice',
 'fresh grapefruit juice',
 'fresh lemon juice',
 'fresh lime juice',
 'fresh orange juice',
 'galliano',
 'gin',
 'gin & ginger ale',
 'ginger ale',
 'ginger ale or soda water',
 'ginger beer',
 'ginger liqueur',
 'gingerbread liqueur',
 'gold rum',
 'grand marnier',
 'grape juice',
 'grapefruit bitters',
 'grapefruit juice',
 'grapefruit flavored vodka',
 'green chartreuse',
 'green creme de menthe',
 'grenadine',
 'half-and-half',
 'heavy cream',
 'hennessy v.s cognac',
 'honey',
 'honey syrup',
 'hot red pepper sauce',
 'hot shot tropical fruit liqueur',
 'hot tea',
 'imported rum',
 'irish cream liqueur',
 'irish whiskey',
 'jalapeno hot pepper sauce',
 'jamaica rum',
 'kirschwasser',
 'kummel',
 'lemon juice',
 'lemon or lime juice',
 'lemon flavored vodka',
 'lemon-lime soda',
 'light cream',
 'light cream (if desired)',
 'light rum',
 'light sweet cream',
 'light vermouth',
 'lillet blanc',
 'lillet rouge',
 'lime juice',
 'lime liqueur',
 'lime vodka',
 'limoncello',
 'madeira',
 'mandarine napoleon liqueur',
 'mango nectar',
 'mango flavored vodka',
 'maple syrup',
 'maraschino liqueur',
 'margarita mix',
 'melon liqueur',
 'mezcal',
 'milk',
 'mint syrup',
 'mint flavored gin',
 'mole bitters',
 'muscatel wine',
 'old kentucky tavern bourbon whiskey',
 'old thompson blended whiskey',
 'olive brine',
 'orange bitters',
 'orange bitters (if desired)',
 'orange blossom water',
 'orange curacao',
 'orange flavored gin',
 'orange juice',
 'orange marmalade',
 'orange flavored vodka',
 'orgeat or almond syrup',
 'orgeat syrup',
 'palo cortado or oloroso sherry',
 'passion fruit juice',
 'passion fruit syrup',
 'peach liqueur',
 'peach schnapps',
 'peach flavored brandy',
 'peychaud bitters',
 "peychaud's bitters",
 'pineapple juice',
 'pineapple or grapefruit juice',
 'pomegranate juice',
 'pomegranate molasses',
 'port',
 'ramazzotti amaro',
 'raspberry ice cream',
 'raspberry juice',
 'raspberry syrup',
 'raspberry yogurt',
 'raspberry flavored liqueur',
 'reposado tequila',
 'rock and rye',
 'root beer',
 'rose water',
 "rose's lime juice",
 'rum',
 'rye or bourbon whiskey',
 'rye whiskey',
 'sake',
 'scotch',
 'scotch whiskey',
 'simple syrup',
 'single-malt scotch whisky',
 'sloe gin',
 'smoky scotch whisky',
 'soda water',
 'sour mix',
 'sparkling wine',
 'straight rye whiskey',
 'strawberry schnapps',
 'strega',
 'sugar syrup',
 'swedish punch',
 'sweet cream',
 'sweet pickle brine',
 'sweet sherry',
 'sweet vermouth',
 'tanqueray gin',
 'tawny port',
 'tennessee whiskey',
 'tequila',
 'tomato juice',
 'triple sec',
 'unsweetened grape juice',
 'v8 cocktail juice',
 'vanilla ice cream',
 'vanilla liqueur',
 'vanilla syrup',
 'vermouth',
 'vinegar',
 'vodka',
 'water',
 'whiskey barrel bitters',
 'white chocolate liqueur',
 'white creme de cacao',
 'white creme de menthe',
 'white curacao',
 'white port wine',
 'wild cherry flavored brandy',
 'worcestershire sauce',
 'yellow chartreuse',
 'amontillado sherry',
 'apricot nectar',
 'aquavit',
 'armagnac',
 'becherovka (czech digestif)',
 'burgundy',
 'cherry liqueur',
 'chile syrup',
 'chilled beer or ale',
 'chilled rhine wine or sauterne',
 'cider',
 'cinnamon schnapps',
 'coconut liqueur',
 'cold brewed black tea',
 'cold brewed chai tea',
 'cold brewed green tea',
 'collins mix',
 'creme de menthe',
 'creme de peche',
 'creme fraiche',
 'fresh celery juice',
 'guava puree',
 'hard cider',
 'hot black coffee',
 'white whiskey',
 'dill pickle brine',
 'georgia moon corn whiskey',
 'grapefruit flavored soda',
 'grapefruit marmalade',
 'grapefruit soda',
 'tonic',
 'tropical fruit schnapps',
 'lychee liqueur',
 'mango juice',
 'manzanilla sherry',
 'mountain dew',
 'oloroso sherry',
 'pastis',
 'pear liqueur',
 'pedro ximenez sherry',
 'iced tea',
 'lavender syrup',
 'pomegranate syrup',
 'red wine',
 'rhubarb syrup',
 'sambuca',
 'drambuie',
 'falernum',
 'pisco',
 'straight rye whisky',
 "pimm's cup",
 'punt e mes']
